services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  
  mock-api:
    image: mock-api:latest
    container_name: mock-api
    build:
      context: ./mountebank
      dockerfile: ./Dockerfile
    volumes:
      - ./mountebank/imposters:/imposters
    ports:
      - 2525:2525
      - 8090:8090
    command: --configfile /imposters/imposters.ejs --allowInjection

  api:
    image: api:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always

volumes:
  mongodb_data:
  mountebank:
